/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as StatsImport } from "./routes/stats";
import { Route as LinearRegressionImport } from "./routes/linear-regression";
import { Route as IndexImport } from "./routes/index";

// Create/Update Routes

const StatsRoute = StatsImport.update({
  id: "/stats",
  path: "/stats",
  getParentRoute: () => rootRoute,
} as any);

const LinearRegressionRoute = LinearRegressionImport.update({
  id: "/linear-regression",
  path: "/linear-regression",
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/linear-regression": {
      id: "/linear-regression";
      path: "/linear-regression";
      fullPath: "/linear-regression";
      preLoaderRoute: typeof LinearRegressionImport;
      parentRoute: typeof rootRoute;
    };
    "/stats": {
      id: "/stats";
      path: "/stats";
      fullPath: "/stats";
      preLoaderRoute: typeof StatsImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/linear-regression": typeof LinearRegressionRoute;
  "/stats": typeof StatsRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/linear-regression": typeof LinearRegressionRoute;
  "/stats": typeof StatsRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/linear-regression": typeof LinearRegressionRoute;
  "/stats": typeof StatsRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/linear-regression" | "/stats";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/linear-regression" | "/stats";
  id: "__root__" | "/" | "/linear-regression" | "/stats";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  LinearRegressionRoute: typeof LinearRegressionRoute;
  StatsRoute: typeof StatsRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LinearRegressionRoute: LinearRegressionRoute,
  StatsRoute: StatsRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/linear-regression",
        "/stats"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/linear-regression": {
      "filePath": "linear-regression.tsx"
    },
    "/stats": {
      "filePath": "stats.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
